version: '3'
volumes:
    taraxa_data:
services:
    taraxa-node:
        container_name: taraxa-node
        image: taraxa/taraxa:1.4.2-26
        restart: always
        ports:
            - "10002:10002"
            - "10002:10002/udp"
            - "7777:7777"
            - "8777:8777"
        expose:
            - "10002"
            - "7777"
            - "8777"
        entrypoint:
            /usr/bin/sh
        command: >
            -c "taraxa config -n testnet -d /var/taraxa -g 0xe414bd813ca44201b5e109d8e8f1aab5db4000d9 &&
                ./docker-entrypoint.sh --conf_taraxa /var/taraxa/conf/private.json --boot_node"
        volumes:
            - taraxa_data:/var/taraxa
